name: Build post-write docker image
on:
  push:
    paths:
      - 'services/post-write/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish post-write to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: saketthakare/post-write:v1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./services/post-write