name: Build comment-read docker image
on:
  push:
    paths:
      - 'services/comment-read/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish comment-read to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: saketthakare/comment-read:v1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./services/comment-read